export const EVENT_TIMEOUT = 5000;

export const TIMEOUT_ERROR_NAME = 'TimeoutError';

export const CLIENTS = {
  TRANSACTIONS_CLIENT: 'TRANSACTIONS_CLIENT',
  MERCHANTS_CLIENT: 'MERCHANTS_CLIENT',
  PAYABLES_CLIENT: 'PAYABLES_CLIENT',
};
